# Generated by Django 3.1.4 on 2020-12-11 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20201211_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='todos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.todo'),
        ),
    ]
